/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tvai' at '6/15/15 7:34 AM' with Gradle 2.3
 *
 * @author tvai, @date 6/15/15 7:34 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
